# This workflow will build a Java project with Maven, run tests, and cache/restore dependencies
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and test with Maven
      run: mvn -B clean test

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run application demo
      run: mvn -B exec:java -Dexec.mainClass="com.example.App"

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      continue-on-error: true
      timeout-minutes: 10

    # Upload test results as artifacts
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/surefire-reports/
        retention-days: 30
