# Security scanning workflow for the security-sandbox project
# This workflow focuses on security-related checks and dependency scanning

name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run security scans weekly
    - cron: '0 2 * * 1'

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # OWASP Dependency Check for vulnerability scanning
    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Security Sandbox'
        path: '.'
        format: 'HTML'
        out: 'reports'

    # Upload security scan results
    - name: Upload OWASP Dependency Check results
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: reports/
        retention-days: 30

    # CodeQL Analysis for security vulnerabilities
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java

    - name: Build with Maven
      run: mvn -B clean compile

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    # Snyk security scanning
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
